return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      { "windwp/nvim-ts-autotag", opts = {} },
      {"nvim-treesitter/nvim-treesitter-context", event = "BufReadPre", opts = { mode = "cursor" }},
    },
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "diff",
        "gitignore",
        "html",
        "http",
        "javascript",
        "jsdoc",
        "jsonc",
        "lua",
        "luap",
        "markdown",
        "markdown_inline",
        "nix",
        "python",
        "regex",
        "rust",
        "scss",
        "sql",
        "svelte",
        "teal",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "json",
      },
      matchup = {
        enable = true,
      },
      highlight = { enable = true },
      query_linter = {
        enable = true,
        use_virtual_text = true,
        lint_events = { "BufWrite", "CursorHold" },
      },
    },
  },
}
